package com.dulcehogar.guis;

import com.dulcehogar.utils.Mensajes;
import com.dulcehogar.utils.Pagos;
import com.dulcehogar.managers.RegistroSocioManager;
import com.dulcehogar.managers.SocioManager;
import com.dulcehogar.utils.Utils;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;

public class ConsultaMontoTotal extends javax.swing.JFrame {
    private Menu menuPrincipal;
    private RegistroSocioManager regSocioManager;
    
    public ConsultaMontoTotal() {
        initComponents();
    }
    
    //Constructor para la ventana de consulta del monto total cancelado por un socio
    public ConsultaMontoTotal(Menu menuPrincipal, RegistroSocioManager regSocioManager) {
        initComponents();
        this.menuPrincipal = menuPrincipal;
        this.regSocioManager = regSocioManager;
        
        // Agregar un WindowsListener para desmarcar el CheckBox al cerrar
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                menuPrincipal.desmarcarCheckbox();
                menuPrincipal.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRut = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        lblMontoTotalCancelado = new javax.swing.JLabel();
        txtMontoTotalCancelado = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DulceHogar - Consulta Monto Total");

        lblRut.setText("Rut");

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });

        lblMontoTotalCancelado.setText("Monto Total Cancelado");

        txtMontoTotalCancelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoTotalCanceladoActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnRegistro.setText("REGISTRO");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistro)
                    .addComponent(btnVolver)
                    .addComponent(lblMontoTotalCancelado)
                    .addComponent(btnBuscar)
                    .addComponent(lblRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoTotalCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblRut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(lblMontoTotalCancelado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMontoTotalCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistro)
                .addGap(14, 14, 14)
                .addComponent(btnVolver)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed
    
    /**
     * Este metodo busca el monto total cancelado por un socio, tambien
     * se encarga de validar el RUT ingresado y muestra el monto total cancelado.
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Obtenemos el RUT ingresado
        String rutIngresado = txtRut.getText().trim();
        
        // Dar formato al RUT del Socio
        String rutFormateado = Utils.formatearRut(rutIngresado);
        if (rutFormateado == null) {
            // Mostramos el mensaje de error si el RUT es invalido
            Mensajes.mostrarError(this, Mensajes.ERROR_RUT);
            return;
        }

        // Buscar socio por RUT
        SocioManager socio = regSocioManager.buscarSocioPorRut(rutFormateado);
        if (socio == null) {
            Mensajes.mostrarError(this, Mensajes.SOCIO_NO_ENCONTRADO);
        } else {
            // Mostrar el monto total cancelado
            txtMontoTotalCancelado.setText(String.valueOf(socio.getCantidadAportada()));
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtMontoTotalCanceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoTotalCanceladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoTotalCanceladoActionPerformed
    
    // Boton para poder volver al menu principal
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        menuPrincipal.setVisible(true);
        // Desmarcar todos los CheckBox del menu principal
        menuPrincipal.desmarcarCheckbox();
        // Cerrar la ventana actual de RegistroSocio
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    
    /**
     * Metodo para mostrar el registro de pagos realizados por un socio,
     * si el socio tiene registros, se muestra en un mensaje, si no, se informa que no tiene pagos.
     */
    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // Obtenemos el RUT y le damos formato
        String rutIngresado = txtRut.getText().trim();
        String rutFormateado = Utils.formatearRut(rutIngresado);

        if (rutFormateado == null) {
            Mensajes.mostrarError(this, Mensajes.ERROR_RUT);
            return;
        }

        SocioManager socio = regSocioManager.buscarSocioPorRut(rutFormateado);
        if (socio == null) {
            Mensajes.mostrarError(this, Mensajes.SOCIO_NO_ENCONTRADO);
            return;
        }

        List<Pagos> pagos = regSocioManager.obtenerPagos(socio.getNumDeSocio());
        if (pagos.isEmpty()) {
            Mensajes.mostrarInfo(this, "El socio no tiene registros de pagos.");
        } else {
            StringBuilder registro = new StringBuilder("Registros de pagos:\n");
            for (Pagos pago : pagos) {
                registro.append(String.format("[%s] Número de Socio: %d Monto: %s\n",
                        pago.getFechaFormateada(),
                        socio.getNumDeSocio(),
                        Utils.formatearDinero(pago.getMonto())
                    )
                );
            }
            JOptionPane.showMessageDialog(this, registro.toString(), "Registro de Pagos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaMontoTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaMontoTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaMontoTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaMontoTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaMontoTotal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblMontoTotalCancelado;
    private javax.swing.JLabel lblRut;
    private javax.swing.JTextField txtMontoTotalCancelado;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
